services:
  - type: web
    name: leads-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2 --preload
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: Admin123!
    # Attach a managed Postgres (you can also use SQLite for testing, but Postgres is recommended in production)
    # To use Render Postgres, create a database in the dashboard and set DATABASE_URL here.
